title: Pixel Pizza
author: dcscode
email: delaneycscode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about videogames, cartoons, and pizza
theme: minima
# social links
twitter_username: dcscode # DO NOT include the @ character, or else the build will fail!
github_username:  dcscode # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
